language: php
php:
  - 7.0

cache:
  directories:
    - "$HOME/.composer/cache"

before_script:
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/tester tests/